config/routes.rb
Rails.application.routes.draw do
  get "home/index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    sessions:      "users/sessions",
    registrations: "users/registrations"
  }

  # Defines the About page route
  get "/about", to: "pages#about", as: "about"
  get "/contact", to: "pages#contact", as: "contact"

  # Defines the admin page route
  get "/admin", to: "pages#admin", as: "admin"
  get "/admin/edit_about", to: "admin#edit_about", as: "edit_about"
  patch "/admin/about", to: "admin#update_about", as: "update_about"

  # Contact content routes
  get "/admin/edit_contact", to: "admin#edit_contact", as: "edit_contact"
  patch "/admin/update_contact", to: "admin#update_contact", as: "update_contact"

  # Defines the root path route ("/")
  root to: "home#index"

  resources :tax_rates, only: %i[index edit update]

  # Product routes
  resources :products, only: %i[show edit update new create destroy] do
    get "variations/:variation", to: "products#index", on: :collection, as: :variation
    get "search", on: :collection # Define the search route within the products resource
  end
  get "/search", to: "products#search"

  # Cart routes
  post "/add_to_cart/:id", to: "cart#add_to_cart", as: "add_to_cart"
  patch "/update_product_quantity/:id", to: "cart#update_product_quantity",
                                        as: "update_product_quantity"
  get "/remove_product/:id", to: "cart#remove_product", as: "remove_product"
  get "/cart", to: "cart#show", as: "cart"

  # API routes
  namespace :api do
    namespace :v1 do
      post :orders, to: "orders#create"
      get "/confirm_order", to: "orders#confirm_order", as: "confirm_order"
      get "/checkout", to: "orders#checkout", as: "checkout"
      get "/order_confirmed", to: "checkout#order_confirmed", as: "order_confirmed"
    end
  end

  resources :users do
    resources :orders, only: %i[index show admin_index admin_show]
  end
end

app/models/about_content.rb
class AboutContent < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact_content.rb
class ContactContent < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  attr_accessor :credit_card_number, :credit_card_exp, :credit_card_cvv

  belongs_to :user
  has_many :order_products
  has_many :products, through: :order_products
  has_one :payment

  validates :base_cost, presence: true, numericality: true
  validates :total_cost, presence: true, numericality: true
  validates :order_status, presence: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :amount, presence: true, numericality: true
  validates :base_cost, presence: true, numericality: true
  validates :gst, numericality: true, allow_nil: true
  validates :pst, numericality: true, allow_nil: true
  validates :hst, numericality: true, allow_nil: true
  validates :total_cost, presence: true, numericality: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products
  has_many :orders, through: :order_products
  has_many :product_variations
  has_many :product_patterns

  validates :name, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 600 }
  validates :outdoor, inclusion: [true, false]
  validates :price, numericality: true, presence: true
  validates :on_sale, numericality: true, presence: true
end

app/models/product_pattern.rb
class ProductPattern < ApplicationRecord
  belongs_to :product

  validates :pattern_name, presence: true
end

app/models/product_variation.rb
class ProductVariation < ApplicationRecord
  belongs_to :product

  validates :variation_name, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :players, dependent: :destroy

  validates :name, presence: true
  validates :gst, numericality: true, allow_nil: true
  validates :pst, numericality: true, allow_nil: true
  validates :hst, numericality: true, allow_nil: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province, optional: true
  has_many :orders, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: { user: 0, admin: 1 }
  after_initialize :set_default_role, if: :new_record?
  def set_default_role
    self.role ||= :user
  end

  attr_writer :login

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value",
                                    { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

  # only allow letter, number, underscore and punctuation.
  validates :username, format: { with: /^[a-zA-Z0-9_.]*$/, multiline: true }

  validate :validate_username

  attr_accessor :province

  validates :full_name, presence: true
  validates :email, format: { with: Devise.email_regexp }
  validates :province, presence: false, on: :create
  validates :encrypted_password, presence: true
  validates_date :birthday, on_or_before: -> { 18.years.ago }
  validates :address, presence: true
  validates :birthday, presence: true
  validates :stripe_id, presence: true

  before_validation :create_on_stripe, on: :create
  def create_on_stripe
    params = { email:, name: full_name }
    response = Stripe::Customer.create(params)
    self.stripe_id = response.id
  end

  def validate_username
    return unless User.where(email: username).exists?

    errors.add(:username, :invalid)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def edit_about
    @about_content = AboutContent.first_or_initialize
  end

  def update_about
    @about_content = AboutContent.first_or_initialize
    @about_content.assign_attributes(content_params)

    if @about_content.save
      redirect_to edit_about_path, notice: "About content updated successfully."
    else
      render :edit_about
    end
  end

  def edit_contact
    @contact_content = ContactContent.first_or_initialize
  end

  def update_contact
    @contact_content = ContactContent.first_or_initialize
    @contact_content.assign_attributes(content_params)

    if @contact_content.update(content_params)
      redirect_to edit_contact_path, notice: "Contact content updated successfully."
    else
      render :edit_contact
    end
  end

  private

  def content_params
    if params[:about_content]
      params.require(:about_content).permit(:content)
    elsif params[:contact_content]
      params.require(:contact_content).permit(:content)
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add_to_cart
    product_id = params[:id]
    Product.find(product_id)

    session[:cart] ||= {}
    session[:cart][product_id] ||= 0
    session[:cart][product_id] += 1

    redirect_to root_path, notice: "Added"
  end

  def update_product_quantity
    product_id = params[:id]
    quantity = params[:quantity].to_i
    session[:cart][product_id] = quantity if session[:cart].key?(product_id)
    redirect_to cart_path, notice: "Quantity updated"
  end

  def remove_product
    product_id = params[:id]
    session[:cart].delete(product_id) if session[:cart].key?(product_id)
    flash[:alert] = "Item removed from cart"
    redirect_to cart_path
  end

  def show; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = if params[:search]
                  Product.where("name LIKE ?", "%#{params[:search]}%").page(params[:page]).per(40)
                else
                  Product.all.page(params[:page]).per(40)
                end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tax_helper.rb
module TaxHelper
end

app/helpers/tax_rates_helper.rb
module TaxRatesHelper
end

app/views/cart/show.html.erb
<div class="max-w-md mx-auto bg-white p-6 rounded-md shadow-md">
  <h1 class="text-2xl font-bold mb-4">Your Cart</h1>

  <% if session[:cart].present? %>
    <div class="">
      <% session[:cart].each do |product_id, quantity| %>
        <% product = Product.find(product_id) %>
        <div class="border rounded mx-auto w-max px-5 mb-4">
          <p class="text-lg mb-2"><%= product.name.titleize %> - Quantity:</p>
          <%= form_tag update_product_quantity_path(id: product.id), method: :patch, class: "flex items-center" do %>
            <%= number_field_tag :quantity, quantity, in: 1..10, class: "border border-gray-300 px-2 py-1 rounded ml-2" %>
            <%= submit_tag 'Update', class: "bg-blue-500 text-white px-3 py-1 rounded ml-2 hover:bg-blue-600 focus:outline-none" %>
          <% end %>
          <%= link_to 'Remove', remove_product_path(product), method: :post, data: { confirm: 'Are you sure?' }, class: "text-red-500 ml-2" %>
        </div>
      <% end %>
    </div>
    <div class="mt-4 sm:grid sm:justify-end">
      <%= link_to 'Checkout', api_v1_checkout_path, class: "bg-green-500 text-white font-bold py-2 px-4 rounded hover:bg-green-600 focus:outline-none" %>
    </div>
  <% else %>
    <p>You need items to check out.</p>
  <% end %>
  <% if flash[:alert] %>
    <p class="text-red-500"><%= flash[:alert] %></p>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="bg-white">
  <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
    <h2 class="text-2xl font-bold tracking-tight text-gray-900">Products</h2>
    <%= render 'partials/name_search_bar' %>
    <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
      <% @products.each do |product| %>
        <div class="group relative">
          <%# <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-gray-200 lg:aspect-none group-hover:opacity-75 lg:h-80">
            On hold until images are figured out.
            <img src="" alt="" class="h-full w-full object-cover object-center lg:h-full lg:w-full">
          </div> %>

          <div class="mt-4 flex justify-between">
            <div>
              <h3 class="text-sm text-gray-700">
                <%= link_to product.name.titleize, product_path(product), class: "absolute inset-0 md:hover:text-blue-700" %>
              </h3>
            </div>
            <p class="text-sm font-medium text-gray-900">$<%= product.price %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="text-center my-4">
    <div class="px-3 py-2 mx-2 text-gray-700 no-underline bg-white rounded-lg">
      <div class="py-4">
        <%= paginate @products %>
      </div>
    </div>
  </div>
</div>