config/routes.rb
Rails.application.routes.draw do
  get "home/index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    sessions:      "users/sessions",
    registrations: "users/registrations"
  }

  # Defines the About page route
  get "/about", to: "pages#about", as: "about"
  get "/contact", to: "pages#contact", as: "contact"

  # Defines the admin page route
  get "/admin", to: "pages#admin", as: "admin"
  get "/admin/edit_about", to: "admin#edit_about", as: "edit_about"
  patch "/admin/about", to: "admin#update_about", as: "update_about"

  # Contact content routes
  get "/admin/edit_contact", to: "admin#edit_contact", as: "edit_contact"
  patch "/admin/update_contact", to: "admin#update_contact", as: "update_contact"

  # Defines the root path route ("/")
  root to: "home#index"

  resources :tax_rates, only: %i[index edit update]

  # Product routes
  resources :products, only: %i[show edit update new create destroy] do
    get "variations/:variation", to: "products#index", on: :collection, as: :variation
    get "search", on: :collection # Define the search route within the products resource
  end
  get "/search", to: "products#search"

  # Cart routes
  post "/add_to_cart/:id", to: "cart#add_to_cart", as: "add_to_cart"
  patch "/update_product_quantity/:id", to: "cart#update_product_quantity",
                                        as: "update_product_quantity"
  get "/remove_product/:id", to: "cart#remove_product", as: "remove_product"
  get "/cart", to: "cart#show", as: "cart"

  # API routes
  namespace :api do
    namespace :v1 do
      post :orders, to: "orders#create"
      get "/confirm_order", to: "orders#confirm_order", as: "confirm_order"
      get "/checkout", to: "orders#checkout", as: "checkout"
      get "/order_confirmed", to: "checkout#order_confirmed", as: "order_confirmed"
    end
  end

  resources :users do
    resources :orders, only: %i[index show admin_index admin_show]
  end
end

app/models/about_content.rb
class AboutContent < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact_content.rb
class ContactContent < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  attr_accessor :credit_card_number, :credit_card_exp, :credit_card_cvv

  belongs_to :user
  has_many :order_products
  has_many :products, through: :order_products
  has_one :payment

  validates :base_cost, presence: true, numericality: true
  validates :total_cost, presence: true, numericality: true
  validates :order_status, presence: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :amount, presence: true, numericality: true
  validates :base_cost, presence: true, numericality: true
  validates :gst, numericality: true, allow_nil: true
  validates :pst, numericality: true, allow_nil: true
  validates :hst, numericality: true, allow_nil: true
  validates :total_cost, presence: true, numericality: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products
  has_many :orders, through: :order_products
  has_many :product_variations
  has_many :product_patterns

  validates :name, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 600 }
  validates :outdoor, inclusion: [true, false]
  validates :price, numericality: true, presence: true
  validates :on_sale, numericality: true, presence: true
end

app/models/product_pattern.rb
class ProductPattern < ApplicationRecord
  belongs_to :product

  validates :pattern_name, presence: true
end

app/models/product_variation.rb
class ProductVariation < ApplicationRecord
  belongs_to :product

  validates :variation_name, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :players, dependent: :destroy

  validates :name, presence: true
  validates :gst, numericality: true, allow_nil: true
  validates :pst, numericality: true, allow_nil: true
  validates :hst, numericality: true, allow_nil: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province, optional: true
  has_many :orders, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: { user: 0, admin: 1 }
  after_initialize :set_default_role, if: :new_record?
  def set_default_role
    self.role ||= :user
  end

  attr_writer :login

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value",
                                    { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

  # only allow letter, number, underscore and punctuation.
  validates :username, format: { with: /^[a-zA-Z0-9_.]*$/, multiline: true }

  validate :validate_username

  attr_accessor :province

  validates :full_name, presence: true
  validates :email, format: { with: Devise.email_regexp }
  validates :province, presence: false, on: :create
  validates :encrypted_password, presence: true
  validates_date :birthday, on_or_before: -> { 18.years.ago }
  validates :address, presence: true
  validates :birthday, presence: true
  validates :stripe_id, presence: true

  before_validation :create_on_stripe, on: :create
  def create_on_stripe
    params = { email:, name: full_name }
    response = Stripe::Customer.create(params)
    self.stripe_id = response.id
  end

  def validate_username
    return unless User.where(email: username).exists?

    errors.add(:username, :invalid)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add_to_cart
    product_id = params[:id]
    Product.find(product_id)

    session[:cart] ||= {}
    session[:cart][product_id] ||= 0
    session[:cart][product_id] += 1

    redirect_to root_path, notice: "Added"
  end

  def update_product_quantity
    product_id = params[:id]
    quantity = params[:quantity].to_i
    session[:cart][product_id] = quantity if session[:cart].key?(product_id)
    redirect_to cart_path, notice: "Quantity updated"
  end

  def remove_product
    product_id = params[:id]
    session[:cart].delete(product_id) if session[:cart].key?(product_id)
    flash[:alert] = "Item removed from cart"
    redirect_to cart_path
  end

  def show; end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tax_helper.rb
module TaxHelper
end

app/helpers/tax_rates_helper.rb
module TaxRatesHelper
end

app/views/admin/edit_about.html.erb
<div class="max-w-2xl mx-auto py-8">
  <div class="bg-white shadow-md rounded px-8 py-6 mb-4">
    <h1 class="text-3xl font-bold mb-4">Edit About</h1>

    <%= form_with(model: @about_content, url: update_about_path, method: :patch) do |form| %>
      <div class="mb-4">
        <%= form.label :content, class: 'block text-gray-700 font-bold mb-2' %>
        <%= form.text_area :content, name: 'about_content[content]', class: 'block w-full border border-gray-300 rounded px-3 py-2 leading-tight focus:outline-none focus:border-blue-500' %>
      </div>
<%= form.submit 'Update About Content', class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded cursor-pointer mr-2' %>
    <% end %>

<%= link_to 'Back to About', about_path, class: 'inline-block mt-4 bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded cursor-pointer ml-2' %>
  </div>
</div>

app/views/admin/edit_contact.html.erb
<div class="max-w-2xl mx-auto py-8">
  <div class="bg-white shadow-md rounded px-8 py-6 mb-4">
    <h1 class="text-3xl font-bold mb-4">Edit Contact</h1>

    <%= form_with(model: @contact_content, url: update_contact_path, method: :patch) do |form| %>
      <div class="mb-4">
        <%= form.label :content, class: 'block text-gray-700 font-bold mb-2' %>
        <%= form.text_area :content, name: 'contact_content[content]', class: 'block w-full border border-gray-300 rounded px-3 py-2 leading-tight focus:outline-none focus:border-blue-500' %>
      </div>
      <%= form.submit 'Update Contact Content', class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %> <!-- Button styling -->
    <% end %>

    <%= link_to 'Back to Contact', contact_path, class: 'block mt-4 text-blue-500 hover:underline' %> <!-- Link styling -->
  </div>
</div>

app/views/admin/update_about.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin#update_about</h1>
  <p>Find me in app/views/admin/update_about.html.erb</p>
</div>

app/views/admin/update_contact.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin#update_contact</h1>
  <p>Contact content updated successfully.</p>
</div>

app/views/checkout/show.html.erb
<div class="max-w-2xl mx-auto py-8">
  <div class="bg-white shadow-md rounded px-8 py-6 mb-4">
    <h1 class="text-3xl font-bold mb-4">Order Confirmation</h1>

    <h2 class="text-2xl font-bold mb-2">Billing Address</h2>
    <p class="mb-2"><%= current_user.full_name.titleize %></p>
    <p class="mb-2"><%= current_user.address.titleize %></p>
    <p class="mb-2"> <%= current_user.postal_code %> - <%= @province.name %></p>
    <p class="mb-2">Canada</p>
    <h2 class="text-2xl font-bold mt-8 mb-4">Order Details</h2>
    <% if @cart_products.any? %>
      <div class="overflow-x-auto">
        <table class="border-collapse w-full mb-8">
          <thead>
            <tr>
              <th class="border border-gray-400 px-4 py-2">Product</th>
              <th class="border border-gray-400 px-4 py-2">Quantity</th>
              <th class="border border-gray-400 px-4 py-2">Price</th>
            </tr>
          </thead>
          <tbody>
            <% @cart_products.each do |item| %>
              <tr class="border border-gray-400">
                <td class="border border-gray-400 px-4 py-2"><%= item[:product].name.titleize %></td>
                <td class="border border-gray-400 px-4 py-2"><%= item[:quantity] %></td>
                <td class="border border-gray-400 px-4 py-2">$ <%= item[:product].price %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <%= form_with url: api_v1_orders_path, method: :post do |form| %>
        <%= form.hidden_field :user_id, value: current_user.id %>
        <div class="flex flex-wrap gap-3 py-5 mb-5 w-full">
          <div class="w-full">
            <div class="relative flex flex-col">
              <%= form.label :credit_card_number, "Card Number", class: "font-bold" %>
              <%= form.text_field :credit_card_number, class: "w-full rounded-md peer pl-2 pr-2 py-2 border-2 border-gray-200 placeholder-gray-300", placeholder: "0000 0000 0000" %>
            </div>
          </div>
          <div class="w-full flex gap-3">
            <div class="w-1/2">
              <%= form.label :credit_card_exp, "Expiration Date", class: "font-bold mb-3" %>
              <%= form.text_field :credit_card_exp, class: "w-full rounded-md peer pl-2 pr-2 py-2 border-2 border-gray-200 placeholder-gray-300", placeholder: "MM/YY" %>
            </div>
            <div class="w-1/2">
              <%= form.label :credit_card_cvv, "CVC/CVV", class: "font-bold mb-3" %>
              <%= form.text_field :credit_card_cvv, class: "w-full rounded-md peer pl-2 pr-2 py-2 border-2 border-gray-200 placeholder-gray-300", placeholder: "CVC/CVV" %>
            </div>
          </div>
          <div class="flex justify-between items-end w-full">
            <div class="">
              <%= form.hidden_field :base_cost, value: @subtotal %>
              <p class="mb-2">Subtotal: $ <%= number_to_currency(@subtotal) %></p>
              <% if @province.gst %>
                <p class="mb-2">GST: $ <%= number_to_currency(@subtotal * @province.gst) %></p>
              <% end %>
              <% if @province.pst %>
                <p class="mb-2">PST: $ <%= number_to_currency(@subtotal * @province.pst) %></p>
              <% end %>
              <% if @province.hst %>
                <p class="mb-2">HST: $ <%= number_to_currency(@subtotal * @province.hst) %></p>
              <% end %>
              <%= form.hidden_field :total_cost, value: @total %>
              <p class="font-bold">Total: $ <%= number_to_currency(@total) %></p>
            </div>
            <div class="justify-self-end">
              <%= form.submit "Confirm Order", class: "bg-green-500 text-white font-bold py-2 px-4 rounded hover:bg-green-600 focus:outline-none" %>
            </div>
          </div>
      </div>
      <% end %>
    <% else %>
      <p>Your cart is empty.</p>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>FurnitureEcommerce</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>

<% if current_user %>
  <nav class="bg-gray-800 py-4">
    <div class="max-w-7xl mx-auto px-4 flex justify-between items-center">
      <ul class="flex space-x-4">
        <!-- Username with Tailwind styling -->
        <li class="uppercase text-yellow-500">
          <%= current_user.username %>
        </li>
        <li>
          <%= link_to 'Home', root_path, class: 'text-white hover:text-gray-300' %>
        </li>
        <li>
          <%= link_to 'About', about_path, class: 'text-white hover:text-gray-300' %>
        </li>
        <li>
          <%= link_to 'Contact', contact_path, class: 'text-white hover:text-gray-300' %>
        </li>
        <li>
          <%= link_to 'My Orders', user_orders_path(current_user), class: 'text-white hover:text-gray-300' %>
        </li>
        <li>
          <% if current_user.admin? %>
        <li>
          <%= link_to 'Admin', admin_path, class: 'text-white hover:text-gray-300' %>
        </li>
          <% end %>
        <li>
          <%= link_to cart_path, class: "relative" do %>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 fill-white">
              <path d="M2.25 2.25a.75.75 0 000 1.5h1.386c.17 0 .318.114.362.278l2.558 9.592a3.752 3.752 0 00-2.806 3.63c0 .414.336.75.75.75h15.75a.75.75 0 000-1.5H5.378A2.25 2.25 0 017.5 15h11.218a.75.75 0 00.674-.421 60.358 60.358 0 002.96-7.228.75.75 0 00-.525-.965A60.864 60.864 0 005.68 4.509l-.232-.867A1.875 1.875 0 003.636 2.25H2.25zM3.75 20.25a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM16.5 20.25a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0z" />
            </svg>
            <% if session[:cart].present? %>
              <span class="flex items-center justify-center absolute -bottom-1 -right-7 bg-red-500 text-white rounded-full h-4 w-4 transform translate-x-2">
                <%= session[:cart].values.sum %>
              </span>
            <% end %>
          <% end %>
        </li>
        <li><%= render 'partials/variations' %></li>
      </ul>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: 'bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded' %>
    </div>
  </nav>
  <%# <p>Hello <%= current_user.username > </p> %>
  <%# <p>You are a [<%= current_user.role >]</p> %>
  <%# <% if current_user.admin? > %>
    <%# <p> There are <%= User.count > users in the system </p> %>
  <%# <% end > %>
<% else %>
  <nav class="bg-gray-800 py-4">
    <div class="max-w-7xl mx-auto px-4 flex justify-between items-center">
      <ul class="flex space-x-4">
        <li>
          <%= link_to 'Home', root_path, class: 'text-white hover:text-gray-300' %>
        </li>
        <li>
          <%= link_to 'About', about_path, class: 'text-white hover:text-gray-300' %>
        </li>
          <li> <%= link_to 'Contact', contact_path, class: 'text-white hover:text-gray-300' %>
        </li>
        <li><%= render 'partials/variations' %></li>
      </ul>
      <div>
        <%= link_to 'Sign Up', new_user_registration_path, class: 'bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded mr-2' %>
        <%= link_to 'Log In', new_user_session_path, class: 'bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded' %>
      </div>
    </div>
  </nav>
<% end %>

<%= yield %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

</body>
</html>

app/views/pages/about.html.erb
<div class="max-w-2xl mx-auto py-8">
  <div class="bg-white shadow-md rounded px-8 py-6 mb-4">
    <h1 class="text-3xl font-bold mb-4">About</h1>
    <p class="text-lg mb-4"><%= @about_content.content %></p>

    <% if current_user&.admin? %>
      <%= link_to 'Admin Panel', edit_about_path, class: 'bg-blue-500 text-white font-bold py-2 px-4 rounded hover:bg-green-700' %>
    <% end %>
  </div>
</div>

app/views/pages/admin.html.erb
<div class="mt-4">
  <%= link_to 'Create New Product', new_product_path, class: 'bg-blue-500 text-white py-2 px-4 rounded-full font-bold hover:bg-blue-700 transition duration-300' %>
  <%= link_to 'Manage Tax Rates', tax_rates_path, class: 'bg-green-500 text-white py-2 px-4 rounded-full font-bold hover:bg-green-700 transition duration-300 ml-4' %>
</div>

app/views/pages/contact.html.erb
<div class="max-w-2xl mx-auto py-8">
  <div class="bg-white shadow-md rounded px-8 py-6 mb-4">
    <h1 class="text-3xl font-bold mb-4">Contact</h1>
    <p class="text-lg mb-4"><%= @contact_content.content %></p>

    <% if current_user&.admin? %>
      <%= link_to 'Admin Panel', edit_contact_path, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
    <% end %>
  </div>
</div>

app/views/partials/_name_search_bar.html.erb
<%= form_tag(search_products_path, method: "get") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search by product name" %>
  <%= select_tag :pattern, options_for_select(ProductPattern.pluck(:pattern_name).uniq, params[:pattern]), include_blank: true %>
  <%= submit_tag "Search" %>
<% end %>

app/views/partials/_variations.html.erb
<% if @variations.present? %>
  <div class="relative inline-block text-left">
    <button class="text-white hover:text-gray-300 px-4 py-2 block" id="variationsDropdown">Variations</button>
    <div class="origin-top-right absolute right-0 mt-2 w-32 rounded-md bg-white shadow-lg z-10" id="variationsContent" style="display: none;">
      <% @variations.each do |variation| %>
        <%= link_to variation, variation_products_path(variation: variation), class: 'block px-4 py-2 text-gray-700 hover:bg-gray-100' %>
      <% end %>
    </div>
    <div class="fixed top-0 left-0 w-full h-full bg-black opacity-25 z-9" id="backdrop" style="display: none;"></div>
  </div>
<% end %>

<!-- Ensure jQuery is included -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Your JavaScript code -->
<script>
  $(document).ready(function() {
    $("#variationsDropdown").on("click", function(event) {
      event.stopPropagation(); // Prevent the event from bubbling up
      $("#variationsContent").toggle();
      $("#backdrop").toggle();
    });

    $(document).on("click", function(event) {
      if (!event.target.matches('#variationsDropdown')) {
        $("#variationsContent").hide();
        $("#backdrop").hide();
      }
    });
  });
</script>