config/routes.rb
Rails.application.routes.draw do
  get "home/index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    sessions:      "users/sessions",
    registrations: "users/registrations"
  }

  # Defines the About page route
  get "/about", to: "pages#about", as: "about"
  get "/contact", to: "pages#contact", as: "contact"

  # Defines the admin page route
  get "/admin", to: "pages#admin", as: "admin"
  get "/admin/edit_about", to: "admin#edit_about", as: "edit_about"
  patch "/admin/about", to: "admin#update_about", as: "update_about"

  # Contact content routes
  get "/admin/edit_contact", to: "admin#edit_contact", as: "edit_contact"
  patch "/admin/update_contact", to: "admin#update_contact", as: "update_contact"

  # Defines the root path route ("/")
  root to: "home#index"

  resources :tax_rates, only: %i[index edit update]

  # Product routes
  resources :products, only: %i[show edit update new create destroy] do
    get "variations/:variation", to: "products#index", on: :collection, as: :variation
    get "search", on: :collection # Define the search route within the products resource
  end
  get "/search", to: "products#search"

  # Cart routes
  post "/add_to_cart/:id", to: "cart#add_to_cart", as: "add_to_cart"
  patch "/update_product_quantity/:id", to: "cart#update_product_quantity",
                                        as: "update_product_quantity"
  get "/remove_product/:id", to: "cart#remove_product", as: "remove_product"
  get "/cart", to: "cart#show", as: "cart"

  # API routes
  namespace :api do
    namespace :v1 do
      post :orders, to: "orders#create"
      get "/confirm_order", to: "orders#confirm_order", as: "confirm_order"
      get "/checkout", to: "orders#checkout", as: "checkout"
      get "/order_confirmed", to: "checkout#order_confirmed", as: "order_confirmed"
    end
  end

  resources :users do
    resources :orders, only: %i[index show admin_index admin_show]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products
  has_many :orders, through: :order_products
  has_many :product_variations
  has_many :product_patterns

  validates :name, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 600 }
  validates :outdoor, inclusion: [true, false]
  validates :price, numericality: true, presence: true
  validates :on_sale, numericality: true, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :set_variations

  def index
    @products = if params[:variation].present?
                  Product.joins(:product_variations).where("product_variations.variation_name = ?",
                                                           params[:variation]).order(:name)
                else
                  Product.order(:name)
                end
  end

  def show
    @product = Product.find(params[:id])

    @variations = @product.product_variations
    @patterns = @product.product_patterns
  end

  def edit; end

  def update
    @product = Product.find(params[:id])
    pattern_names = params[:product][:pattern_names] # Fetch selected pattern names from params

    # Clear existing associations to reassign the patterns
    @product.product_patterns.destroy_all

    if @product.update(product_params)
      # Associate each selected pattern with the updated product
      pattern_names.each do |pattern_name|
        selected_pattern = ProductPattern.find_by(pattern_name:)
        @product.product_patterns.create(pattern_name:) if selected_pattern
      end

      redirect_to @product, notice: "Product was successfully updated."
    else
      render :edit
    end
  end

  def new
    @product = Product.new
    @patterns = ProductPattern.pluck(:pattern_name, :id) # Fetch pattern names and IDs
  end

  def create
    @product = Product.new(product_params)
    pattern_names = params[:product][:pattern_names] # Fetch selected pattern names from params

    if @product.save
      # Associate each selected pattern with the newly created product
      pattern_names.each do |pattern_name|
        selected_pattern = ProductPattern.find_by(pattern_name:)
        @product.product_patterns.create(pattern_name:) if selected_pattern
      end

      redirect_to @product, notice: "Product was successfully created."
    else
      render :new
    end
  end

  def destroy
    @product.destroy
    redirect_to root_path, notice: "Product was successfully deleted."
  end

  def search
    Rails.logger.debug "Search Param: #{params[:search]}"
    Rails.logger.debug "Pattern Param: #{params[:pattern]}"
    @products = Product.includes(:product_patterns)

    @products = @products.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?

    @products = @products.where(product_patterns: { pattern_name: params[:pattern] }) if params[:pattern].present?

    @products = @products.page(params[:page]).per(10)

    render "home/index"
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :outdoor, :on_sale, :description, :pattern)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<div class="max-w-md mx-auto bg-white p-6 rounded-md shadow-md">
  <h1 class="text-2xl font-bold mb-4">Edit Product</h1>

  <%= form_for @product, url: product_path(@product), method: :patch do |f| %>
    <div class="mb-4">
      <%= f.label :name, class: "block text-gray-700 font-bold mb-2" %>
      <%= f.text_field :name, class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>

    <div class="mb-4">
      <%= f.label :price, class: "block text-gray-700 font-bold mb-2" %>
      <%= f.number_field :price, step: '0.01', class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>

    <div class="mb-4">
      <%= f.label :outdoor, class: "flex items-center" %>
      <%= f.check_box :outdoor, class: "form-checkbox h-5 w-5 text-indigo-600" %>
      <span class="ml-2 text-gray-700 font-bold">Outdoor</span>
    </div>

    <div class="mb-4">
      <%= f.label :on_sale, class: "block text-gray-700 font-bold mb-2" %>
      <%= f.number_field :on_sale, step: '0.01', class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>

    <div class="grid grid-cols-2 gap-4 mb-4">
      <% ProductPattern.pluck(:pattern_name).uniq.each do |pattern_name| %>
        <div>
          <%= check_box_tag 'product[pattern_names][]', pattern_name, @product.product_patterns.exists?(pattern_name: pattern_name), class: "form-checkbox h-5 w-5 text-indigo-600" %>
          <%= label_tag "product_pattern_#{pattern_name}", pattern_name, class: "ml-2 text-gray-700 font-bold" %>
        </div>
      <% end %>
    </div>

    <div class="mb-4">
      <%= f.label :description, class: "block text-gray-700 font-bold mb-2" %>
      <%= f.text_area :description, class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>

    <div class="text-center">
      <%= f.submit "Update Product", class: "px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 transition duration-300" %>
    </div>
    <div class="text-center mt-4">
      <%= button_to "Delete Product", @product, method: :delete, data: { confirm: 'Are you sure?' }, class: "px-4 py-2 bg-red-500 text-white rounded-md hover:bg-red-700 transition duration-300" %>
    </div>
  <% end %>
</div>

app/views/products/index.html.erb
<!-- app/views/products/_filtered_products.html.erb -->
<div class="bg-white">
  <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
    <h2 class="text-2xl font-bold tracking-tight text-gray-900">Filtered Products</h2>
    <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
      <% @products.each do |product| %>
        <div class="group relative">
          <!-- Your product card or item structure here -->
          <div class="mt-4 flex justify-between">
            <div>
              <h3 class="text-sm text-gray-700">
                <%= link_to product.name.titleize, product_path(product), class: "absolute inset-0 md:hover:text-blue-700" %>
              </h3>
            </div>
            <p class="text-sm font-medium text-gray-900">$<%= product.price %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <!-- Pagination if needed -->
  <div class="text-center my-4">
    <div role="navigation" aria-label="Pagination" class="px-3 py-2 mx-2 text-gray-700 no-underline bg-white rounded-lg">
      <div class="py-4">
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="max-w-md mx-auto bg-white p-6 rounded-md shadow-md">
  <h1 class="text-2xl font-bold mb-4">New Product</h1>
  <%= form_for @product, url: products_path, method: :post do |f| %>
    <div class="mb-4">
      <%= f.label :name, class: "block text-gray-700 font-bold mb-2" %>
      <%= f.text_field :name, class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>
    <div class="mb-4">
      <%= f.label :price, class: "block text-gray-700 font-bold mb-2" %>
      <%= f.number_field :price, step: '0.01', class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>
    <div class="mb-4">
      <%= f.label :outdoor, class: "flex items-center" %>
      <%= f.check_box :outdoor, class: "form-checkbox h-5 w-5 text-indigo-600" %>
      <span class="ml-2 text-gray-700 font-bold">Outdoor</span>
    </div>
    <div class="mb-4">
      <%= f.label :on_sale, class: "block text-gray-700 font-bold mb-2" %>
      <%= f.number_field :on_sale, step: '0.01', class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>

    <div class="grid grid-cols-2 gap-4 mb-4">
      <% ProductPattern.pluck(:pattern_name).uniq.each do |pattern_name| %>
        <div>
          <%= check_box_tag 'product[pattern_names][]', pattern_name, @product.product_patterns.exists?(pattern_name: pattern_name), class: "form-checkbox h-5 w-5 text-indigo-600" %>
          <%= label_tag "product_pattern_#{pattern_name}", pattern_name, class: "ml-2 text-gray-700 font-bold" %>
        </div>
      <% end %>
    </div>

    <div class="mb-4">
      <%= f.label :description, class: "block text-gray-700 font-bold mb-2" %>
      <%= f.text_area :description, class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>
    <div class="text-center">
      <%= f.submit "Create Product", class: "px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 transition duration-300" %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="bg-gray-100 dark:bg-gray-800 py-8">
    <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex flex-col md:flex-row -mx-4">
            <div class="md:flex-1 px-4">
                    <div class="h-[460px] rounded-lg bg-gray-300 dark:bg-gray-700 mb-4">
          <%# Use Unsplash URL with product name as a query parameter %>
          <% image_url = "https://source.unsplash.com/featured/?#{@product.name.parameterize}" %>
          <img class="w-full h-full object-cover" src="<%= image_url %>" alt="Product Image">
        </div>
                <%# <div class="h-[460px] rounded-lg bg-gray-300 dark:bg-gray-700 mb-4">
                    <img class="w-full h-full object-cover" src="https://cdn.pixabay.com/photo/2020/05/22/17/53/mockup-5206355_960_720.jpg" alt="Product Image">
                    On hold until images are figured out.
                </div> %>
                <div class="flex -mx-2 mb-4">
                    <div class="w-1/2 px-2">
                        <%= link_to 'Add to Cart', add_to_cart_path(@product.id), data: {turbo_method: :post}, class: "w-full bg-gray-900 dark:bg-gray-600 text-white py-2 px-4 rounded-full font-bold hover:bg-gray-800 dark:hover:bg-gray-700" %>
                        <%# <button class="w-full bg-gray-900 dark:bg-gray-600 text-white py-2 px-4 rounded-full font-bold hover:bg-gray-800 dark:hover:bg-gray-700">Add to Cart</button> %>
                    </div>
                </div>
            </div>
            <div class="md:flex-1 px-4">
                <h2 class="text-2xl font-bold text-gray-800 dark:text-white mb-2"><%= @product.name.titleize %></h2>
                <div class="flex mb-4">
                    <div class="mr-4">
                        <span class="font-bold text-gray-700 dark:text-gray-300">Price:</span>
                        <span class="text-gray-600 dark:text-gray-300">$<%= @product.price %></span>
                    </div>
                </div>
                <div class="mb-4">
                    <% if @variations.any? then %>
                      <span class="font-bold text-gray-700 dark:text-gray-300">Select Variation:</span>
                      <div class="flex items-center mt-2">
                        <% @variations.each do |variation| %>
                          <button class="variation-button bg-gray-300 dark:bg-gray-700 text-gray-700 dark:text-white py-2 px-4 rounded-full font-bold mr-2 hover:bg-gray-400 dark:hover:bg-gray-600 whitespace-nowrap"><%= variation.variation_name.titleize %></button>
                        <% end %>
                      </div>
                    <% end %>
                </div>
                <div>
                  <span class="font-bold text-gray-700 dark:text-gray-300">Product Variation:</span>
                  <span class="text-gray-600 dark:text-gray-300"><%= @product.product_variations.first&.variation_name %></span>
                </div>
                <div class="mb-4">
                    <% if @patterns.any? then %>
                      <span class="font-bold text-gray-700 dark:text-gray-300">Select Pattern:</span>
                      <div class="flex items-center mt-2">
                        <% @patterns.each do |pattern| %>
                          <button class="pattern-button bg-gray-300 dark:bg-gray-700 text-gray-700 dark:text-white py-2 px-4 rounded-full font-bold mr-2 hover:bg-gray-400 dark:hover:bg-gray-600 whitespace-nowrap"><%= pattern.pattern_name.titleize %></button>
                        <% end %>
                      </div>
                    <% end %>
                </div>
                <div>
                    <span class="font-bold text-gray-700 dark:text-gray-300">Product Description:</span>
                    <p class="text-gray-600 dark:text-gray-300 text-sm mt-2">
                      <%= @product.description%>
                    </p>
                </div>
                <div class="flex -mx-2 mb-4">
                  <div class="w-1/2 px-2">
                    <% if current_user&.admin? %>
                      <%= link_to 'Admin Panel', edit_product_path(@product), class: 'bg-blue-500 dark:bg-gray-600 text-white py-2 px-4 rounded-full font-bold hover:bg-gray-800 dark:hover:bg-gray-700 inline-block mt-2' %>
                    <% end %>
                  </div>
              </div>
            </div>
        </div>
    </div>
</div>